### ISSUE TITLE
building maps

### ISSUE THREAD

**Issue by ddwy** [srmainwaring/curio#11]
Hello, there is only navigation in the code given, is there a module for building maps?

**Comment by srmainwaring** [comment]
@ddwy to build maps you would use the standard ROS modules from the navigation stack and follow the [navigation tutorials](http://wiki.ros.org/navigation/Tutorials). I have used the method described in the tutorial [slam_gmappingTutorialsMappingFromLoggedData](http://wiki.ros.org/slam_gmapping/Tutorials/MappingFromLoggedData) and found it worked well.

This PR [Add navigation of simulated curio #10](https://github.com/srmainwaring/curio/pull/10/files) contains a nice example in simulation.

**Comment by srmainwaring** [comment]
Closed by PR #10
