### ISSUE TITLE
ackermann_drive_controller question: how to change axis?

### ISSUE THREAD

**Issue by markgatland** [srmainwaring/curio#16]
Hello, apologies since this is not really an issue with getting the project to work, but it is to do with the code.
I'm trying to retrofit the ackermann_drive_controller package from this repository into the [curiosity_mars_rover](https://discourse.ros.org/t/the-nasa-curiosity-rover-rosject-is-now-open-source/7635) ROS robot, and I think I almost have it working but there is a problem. Steering messages are functioning but they seem to be rotated 90 degrees in the wrong direction, whilst velocity messages for moving forward/backward are simply doing nothing.

Upon further inspection of Curio's definition vs the curiosity_mars_rover's , it appears that the two robots are defined along different axes. The front of Curio faces the same direction as the red arrow (positive X axis), whereas the front of Curiosity faces the opposite direction of the green arrow (negative Y axis). Therefore, I'm under the impression that the ackermann_drive_controller is telling the wheels to move in a direction they can't move, causing the issue.

I might be wrong about that, but regardless my question is, how can I modify the ackermann_drive_controller to account for this? After a quick bit of research it looks like best practice is for models to face the positive X axis. I could theoretically edit the Curiosity URDF files to rotate everything 90 degrees to the left, but I'm wondering if there is a more programmatic solution to this problem.

Thanks!

**Comment by srmainwaring** [comment]
Hi @markgatland, the orientation conventions for ROS are defined in https://www.ros.org/reps/rep-0105.html which recommend the forward direction is aligned with the positive x-axis, y left and z up. The Curio stack is consistent with this convention, not just for the drive controller, but also for integration with the navigation stack, gazebo, etc. Your best bet is to rotate the Curiosity base link to standard conventions - sometimes there are parameters available to do this in a launch file when loading the robot description, but failing that you may need to edit the xacro or urdf as you suggest. It has to happen at this level as everything else drives off that.

**Comment by markgatland** [comment]
Okay, I see. I just tried rotating everything and now it is working with the ackermann_drive_controller! 
Thanks for the info.
